AutoPass/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

autopass/curator/urls.py
__all__ = []
import django.urls

import curator.views

app_name = "curator"


urlpatterns = [
    django.urls.path(
        "requests/",
        curator.views.PassRequestsView.as_view(),
        name="pass-requests",
    ),
]

autopass/homepage/urls.py
__all__ = ()

from django.urls import path

from homepage.views import HomeView

app_name = "homepage"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
]

autopass/passes/urls.py
import django.urls

import passes.views

app_name = "passes"


urlpatterns = [
    django.urls.path("groups/", passes.views.GroupsView.as_view(), name="groups"),
    django.urls.path(
        "groups/<int:group_id>/download/",
        passes.views.DownloadAllGroupPassesView.as_view(),
        name="download_group_passes",
    ),
]

autopass/users/urls.py
__all__ = []
import django.contrib.auth.views
from django.urls import path

import users.forms
import users.views

app_name = "users"

urlpatterns = [
    path(
        "login/student",
        django.contrib.auth.views.LoginView.as_view(
            template_name="users/login-student.html",
            authentication_form=users.forms.LoginCode,
        ),
        name="login-student",
    ),
    path(
        "login/curator",
        django.contrib.auth.views.LoginView.as_view(
            template_name="users/login-curator.html",
            authentication_form=users.forms.LoginForm,
        ),
        name="login-curator",
    ),
    path(
        "logout/",
        django.contrib.auth.views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "signup/",
        users.views.SignUpView.as_view(),
        name="signup",
    ),
    path(
        "activate/<str:username>/",
        users.views.ActivateUserView.as_view(),
        name="activate",
    ),
    path("profile/avatar/", users.views.UploadAvatarPageView.as_view(), name="profile"),
    path(
        "avatar/upload/api/",
        users.views.UploadAvatarApiView.as_view(),
        name="upload-avatar-api",
    ),
    path("upload/", users.views.UploadStudentsView.as_view(), name="upload-students"),
    path(
        "upload/result/<str:group_name>/",
        users.views.UploadResultView.as_view(),
        name="upload-result",
    ),
    path("reset/", users.views.ResetStudentsView.as_view(), name="reset"),
]

autopass/pass/models.py
__all__ = ()

import django.contrib.auth.models
import django.db.models
from django.utils.translation import gettext_lazy as _


class Pass(django.db.models):

    class RatingChoices(django.db.models.TextChoices):
        NotVerify = "NotUnVerify", _('Не проверен')
        Verify = "Verify", _('Проверен')
        Printed = "Printed", _('Нейтрально')


    photo = django.db.models.ImageField(
        upload_to="pass_photo/%Y/%m/%d/",
        verbose_name=_("Фото на пропуск"),
    )
    user = django.db.models.OneToOneField(
        django.contrib.auth.models.User,
        on_delete=django.db.models.CASCADE,
    )
    status = django.db.models.CharField(
        'статус',
        choices=,
        default='received',
    )

autopass/curator/views.py
__all__ = ("CuratorRequiredMixin", "PassRequestsView")
import django.contrib.auth.decorators
import django.http
import django.shortcuts
import django.urls
import django.utils.decorators
import django.views.generic

import passes.models
import users.models


class CuratorRequiredMixin:
    @django.utils.decorators.method_decorator(
        django.contrib.auth.decorators.login_required,
    )
    def dispatch(self, request, *args, **kwargs):
        if request.user.profile.role != "куратор":
            return django.http.HttpResponseNotFound()

        return super().dispatch(request, *args, **kwargs)


class PassRequestsView(CuratorRequiredMixin, django.views.generic.ListView):
    template_name = "curator/pass_requests.html"
    context_object_name = "passes"

    def get_queryset(self):
        led_groups = users.models.GroupLeader.objects.filter(curator=self.request.user)
        group_ids = led_groups.values_list("group__id", flat=True)
        return passes.models.Pass.objects.filter(
            user__groups__id__in=group_ids,
            status__in=[
                "NotFilledIn",
                "NotVerify",
            ],
        ).order_by("user__groups__name")

    def post(self, request, *args, **kwargs):
        pass_id = request.POST.get("pass_id")
        status = request.POST.get("status")

        if pass_id and status in ["Verify", "NotFilledIn"]:
            try:
                pass_obj = passes.models.Pass.objects.get(id=pass_id)
                pass_obj.status = status
                pass_obj.save()
            except passes.models.Pass.DoesNotExist:
                pass

        return django.shortcuts.redirect("curator:pass-requests")

autopass/homepage/views.py
__all__ = ()

import django.views.generic


class HomeView(django.views.generic.TemplateView):
    template_name = "homepage/home.html"
    context_object_name = "items"

autopass/passes/views.py
__all__ = ()

import shutil
import tempfile

import django.contrib
import django.contrib.admin.views.decorators
import django.views.generic

import card_maker.card_maker
import passes.models


@django.utils.decorators.method_decorator(
    django.contrib.admin.views.decorators.staff_member_required,
    name="dispatch",
)
class GroupsView(django.views.generic.ListView):
    template_name = "passes/group.html"
    context_object_name = "groups"
    model = django.contrib.auth.models.Group

    def get_queryset(self):
        return django.contrib.auth.models.Group.objects.all()


@django.utils.decorators.method_decorator(
    django.contrib.admin.views.decorators.staff_member_required,
    name="dispatch",
)
class DownloadAllGroupPassesView(django.views.generic.View):
    def get(self, request, group_id):

        group = django.contrib.auth.models.Group.objects.get(pk=group_id)
        passes_list = passes.models.Pass.objects.filter(
            user__groups=group,
            status="Verify",
        )

        with tempfile.TemporaryDirectory() as temp_dir:
            for pass_obj in passes_list:
                name = f"{pass_obj.user.first_name} {pass_obj.user.last_name}"

                im = card_maker.card_maker.ImageEditor(
                    template_path="template.png",
                    output_path=temp_dir,
                    circle_size=(760, 760),
                    photo_position=(155, 165),
                    text_position=(950, 600),
                )

                im.create_final_image(
                    image_path=pass_obj.user.profile.avatar.path,
                    text=name,
                    final_name=f"{name}.png",
                )

            zip_path = f"/tmp/{group.name}.zip"
            shutil.make_archive(zip_path.replace(".zip", ""), "zip", temp_dir)

            with open(zip_path, "rb") as f:
                file_content = f.read()

            response = django.http.HttpResponse(
                file_content,
                content_type="application/zip",
            )
            response["Content-Disposition"] = f'attachment; filename="{group.name}.zip"'
            return response

autopass/users/views.py
__all__ = (
    "ActivateUserView",
    "SignUpView",
    "UploadAvatarApiView",
    "UploadAvatarPageView",
)
from datetime import timedelta
import os
import tempfile

import django.conf
import django.contrib.auth.decorators
import django.contrib.auth.models
import django.contrib.messages
import django.core.files.base
import django.core.mail
import django.http
import django.shortcuts
import django.urls
import django.utils.decorators
import django.utils.timezone
import django.views.generic

import curator.views
import passes.models
import users.forms
import users.models
import users.utils


class SignUpView(django.views.generic.View):
    def get(self, request):
        personal_form = users.forms.SignupForm()
        return django.shortcuts.render(
            request,
            "users/signup.html",
            {
                "personal_form": personal_form,
            },
        )

    def post(self, request):
        personal_form = users.forms.SignupForm(request.POST)
        if personal_form.is_valid():
            user = personal_form.save(commit=False)
            user.is_active = django.conf.settings.DEFAULT_USER_IS_ACTIVE
            user.save()
            users.models.Profile.objects.create(
                user=user,
                role="куратор",
            )

            if not user.is_active:
                django.core.mail.send_mail(
                    subject="Подтвердите вашу почту",
                    message="Для подтверждения почты перейдите по ссылке"
                    f" - /activate/{user.username}",
                    from_email=django.conf.settings.DEFAULT_FROM_EMAIL,
                    recipient_list=[
                        users.models.User.objects.normalize_email(user.email),
                    ],
                    fail_silently=False,
                )

            return django.shortcuts.redirect("users:login-curator")

        return django.shortcuts.render(
            request,
            "users/signup.html",
            {
                "personal_form": personal_form,
            },
        )


class ActivateUserView(django.views.generic.View):

    def get(self, request, username):
        try:
            base_query = django.contrib.auth.models.User.objects
            user = base_query.get(username=username)
            try:
                user_profile = user.profile
                if user_profile.attempts_time is not None:
                    if (
                        django.utils.timezone.now() - user_profile.attempts_time
                        <= timedelta(
                            days=7,
                        )
                    ):
                        user.is_active = True
                        user.save()
                        user_profile.attempts_time = None
                        user_profile.attempts_count = 0
                        user_profile.save()
                        return django.shortcuts.render(
                            request,
                            "users/activate_done.html",
                        )

            except Exception:
                pass

            user = base_query.get(username=username)
            if user.profile.attempts_time is None:
                if django.utils.timezone.now() - user.date_joined <= timedelta(
                    hours=12,
                ):
                    user.is_active = True
                    user.save()
                    return django.shortcuts.render(
                        request,
                        "users/activate_done.html",
                    )

        except Exception:

            raise django.http.Http404()

        raise django.http.Http404()


@django.utils.decorators.method_decorator(
    django.contrib.auth.decorators.login_required,
    name="dispatch",
)
class UploadAvatarPageView(django.views.generic.View):

    def get(self, request):
        if request.user.profile.role == "куратор":
            return django.http.HttpResponseNotFound()

        return django.shortcuts.render(request, "users/profile_form.html")


@django.utils.decorators.method_decorator(
    django.contrib.auth.decorators.login_required,
    name="dispatch",
)
class UploadAvatarApiView(django.views.generic.View):
    def post(self, request):
        if request.user.profile.role == "куратор":
            return django.http.HttpResponseNotFound()

        if "avatar" not in request.FILES:
            return django.http.JsonResponse(
                {"status": "error", "message": "Файл не найден"},
                status=400,
            )

        try:
            avatar_file = request.FILES["avatar"]

            if avatar_file.size > 5 * 1024 * 1024:
                return django.http.JsonResponse(
                    {"status": "error", "message": "Файл слишком большой (макс. 5MB)"},
                    status=400,
                )

            profile = request.user.profile

            if profile.avatar:
                profile.avatar.delete(save=False)

            profile.avatar.save(
                f"avatar_{request.user.id}.jpg",
                django.core.files.base.ContentFile(avatar_file.read()),
            )
            profile.save()

            passes.models.Pass.objects.filter(user=request.user).update(
                status="NotVerify",
            )
            return django.http.JsonResponse(
                {
                    "status": "success",
                    "message": "Фото успешно загружено",
                    "avatar_url": profile.avatar.url,
                },
            )

        except Exception:
            return django.http.JsonResponse(
                {"status": "error", "message": "Ошибка сервера"},
                status=500,
            )


class UploadStudentsView(
    curator.views.CuratorRequiredMixin,
    django.views.generic.FormView,
):
    template_name = "pdf/upload_students.html"
    form_class = users.forms.UploadFileForm

    def form_valid(self, form):
        group_name = form.cleaned_data["group_name"]
        uploaded_file = form.cleaned_data["file"]
        delimiter = form.cleaned_data["delimiter"] or ","

        try:
            django.contrib.auth.models.Group.objects.get(name=group_name)
            form.add_error(
                "group_name",
                f"Группа с названием '{group_name}' уже существует",
            )
            return self.form_invalid(form)
        except django.contrib.auth.models.Group.DoesNotExist:
            pass

        with tempfile.NamedTemporaryFile(
            delete=False,
            suffix=os.path.splitext(uploaded_file.name)[1].lower(),
        ) as temp_file:
            for chunk in uploaded_file.chunks():
                temp_file.write(chunk)

            temp_file_path = temp_file.name

        try:
            group = django.contrib.auth.models.Group.objects.create(name=group_name)

            users.utils.get_file(
                file_path=temp_file_path,
                group_name=group_name,
                delimiter=delimiter,
            )
            users.models.GroupLeader.objects.create(
                group=group,
                curator=self.request.user,
            )
            django.core.mail.send_mail(
                subject=f"Создана группа {group_name}",
                message="Для получения логинов перейдите по ссылке"
                f" - /users/upload/result/{group_name}",
                from_email=django.conf.settings.DEFAULT_FROM_EMAIL,
                recipient_list=[
                    self.request.user.email,
                ],
                fail_silently=False,
            )

            return django.shortcuts.redirect(
                django.urls.reverse(
                    "users:upload-result",
                    kwargs={"group_name": group_name},
                ),
            )

        except Exception:
            group.delete()
            form.add_error("file", "Ошибка файла")
            return self.form_invalid(form)

        finally:
            if os.path.exists(temp_file_path):
                os.unlink(temp_file_path)


@django.utils.decorators.method_decorator(
    django.contrib.auth.decorators.login_required,
    name="dispatch",
)
class UploadResultView(django.views.generic.TemplateView):
    template_name = "pdf/upload_result.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.profile.role != "куратор":
            return django.http.HttpResponseNotFound()

        group_name = self.kwargs.get("group_name")

        try:
            group = django.contrib.auth.models.Group.objects.get(name=group_name)
        except django.contrib.auth.models.Group.DoesNotExist:
            return django.http.HttpResponseNotFound()

        try:
            users.models.GroupLeader.objects.get(group=group, curator=request.user)
        except users.models.GroupLeader.DoesNotExist:
            return django.http.HttpResponseNotFound()

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        group_name = self.kwargs.get("group_name")

        html_content = users.utils.create_pdf(group_name)
        context["generated_html"] = html_content
        context["group_name"] = group_name

        return context


class ResetStudentsView(
    curator.views.CuratorRequiredMixin,
    django.views.generic.FormView,
):
    template_name = "pdf/reset_students.html"
    form_class = users.forms.ResetStudent

    def form_valid(self, form):
        token = form.cleaned_data["token"]
        user = users.models.User.objects.filter(username=token)
        if not user.exists() or (user := user.first()).profile.role != "ученик":
            form.add_error(
                "token",
                "Такой студент не существует или у вас нет прав на его изменения",
            )
            return self.form_invalid(form)

        group = user.groups.first()
        try:

autopass/templates/includes/footer.html
{% load i18n %}
{% with request.resolver_match.view_name as view_name %}
  <footer class="py-3 my-4">


    <div class="text-center text-body-secondary">&copy; <span id="years">{% now "c" %}</span>
      Company, Inc
    </div>
  </footer>
{% endwith %}


<script>
  function Time() {
    const server = new Date("{% now 'Y-m-d\\TH:i:s' %}Z").getTime();
    const client = Date.now();
    const diff = Math.abs(client - server)
    const diff_hours = diff / (1000 * 60 * 60)
    if (diff_hours <= 24) {
      return new Date(client).getFullYear();
    } else {
      return new Date(server).getFullYear();
    }
  }

  document.getElementById("years").innerHTML = Time();
</script>

autopass/templates/includes/form.html
<form method="post">
    {% csrf_token %}
    {% if form.non_field_errors %}
        <div class="alert alert-danger">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
    {% endif %}
    {% for field in form %}
        <div class="mb-3">
            <label class="form-label">
                {{ field.label }}
                {% if field.field.required %}<span class="text-danger">*</span>{% endif %}
            </label>
            {{ field }}
            {% if field.help_text %}
                <div class="form-text">{{ field.help_text }}</div>
            {% endif %}
            {% if field.errors %}
                <div class="text-danger small">
                    {% for error in field.errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary w-100">{{ button_text|default:"Отправить" }}</button>
</form>

autopass/templates/includes/header.html
{% load static %}
{% load i18n %}
{% with request.resolver_match.view_name as view_name %}
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-warning border-bottom">
    <div class="container">
      <a class="navbar-brand d-flex align-items-center me-auto" href="{% url 'homepage:home' %}">
        <img
          src="{% static 'favicon/favicon-32x32.ico' %}"
          alt="Logo"
          width="32"
          height="32"
          class="me-2"
        >
        <span class="fw-semibold text-dark">AutoPass</span>
      </a>

      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#mainNavbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="mainNavbar">
        <div class="d-flex gap-2 align-items-center">
          {% if user.is_authenticated %}
            {% if user.profile.role != "куратор" %}
              <a href="{% url 'users:profile' %}" class="btn btn-outline-dark btn-sm d-flex align-items-center">
                <i class="bi bi-person-circle me-1"></i>
                <span>{{ user.first_name }} {{ user.last_name }} {{ user.profile.middle_name }}</span>
              </a>
            {% else %}
              <a href="{% url 'users:upload-students' %}" class="btn btn-outline-dark btn-sm d-flex align-items-center">
                <i class="bi bi-upload me-1"></i>
                <span>Добавить учеников</span>
              </a>
              <a href="{% url 'users:reset' %}" class="btn btn-outline-dark btn-sm d-flex align-items-center">
                <i class="bi bi-arrow-repeat me-1"></i>
                <span>Сбросить ученика</span>
              </a>
              <a href="{% url 'curator:pass-requests' %}" class="btn btn-outline-dark btn-sm d-flex align-items-center">
                <i class="bi bi-card-checklist me-1"></i>
                <span>Отобрать</span>
              </a>
            {% endif %}
            {% if request.user.is_authenticated and request.user.is_staff %}
                <a class="btn btn-outline-dark btn-sm d-flex align-items-center" href="{% url 'admin:index' %}">Админ панель</a>
                <a class="btn btn-outline-dark btn-sm d-flex align-items-center" href="{% url 'passes:groups' %}">Печать</a>

            {% endif %}
            <form method="post" action="{% url 'users:logout' %}" class="m-0">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm d-flex align-items-center">
                <i class="bi bi-box-arrow-right me-1"></i>
                <span>Выйти</span>
              </button>
            </form>

          {% else %}
            <a href="{% url 'users:login-student' %}" class="btn btn-outline-dark btn-sm d-flex align-items-center">
              <i class="bi bi-box-arrow-in-right me-1"></i>
              <span>Войти</span>
            </a>

            <a href="{% url 'users:signup' %}" class="btn btn-dark btn-sm d-flex align-items-center">
              <i class="bi bi-person-plus me-1"></i>
              <span>Регистрация</span>
            </a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header>
{% endwith %}